apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "python-app.fullname" . }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
spec:
  groups:
    - name: {{ include "python-app.fullname" . }}.rules
      rules:
        - alert: HighErrorRate
          expr: |
            (
              sum(rate(flask_http_request_total{app_name="{{ .Values.nameOverride }}", status=~"5.."}[5m]))
              /
              sum(rate(flask_http_request_total{app_name="{{ .Values.nameOverride }}"}[5m]))
            ) > 0.05
          for: 2m
          labels:
            severity: warning
            app_name: {{ .Values.nameOverride }}
          annotations:
            summary: "High error rate on {{ include "python-app.fullname" . }}"
            description: "Error rate for {{ include "python-app.fullname" . }} has been above 5% for more than 2 minutes."
