apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Python app that displays the time. Name ${{values.app_name}}
  # Example for optional annotations
  annotations:
    github.com/project-slug: zahra-ehghaghi-org/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
