apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        hosts {
           140.82.112.4 github.com
           140.82.121.5 api.github.com
           13.107.42.16 vstoken.actions.githubusercontent.com
           13.107.42.16 pipelines.actions.githubusercontent.com
           140.82.121.10 codeload.github.com
           140.82.112.21 results-receiver.actions.githubusercontent.com
           185.199.110.133 objects.githubusercontent.com
           13.107.42.16 pipelinesghubeus10.actions.githubusercontent.com

           fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30 {
           disable success cluster.local
           disable denial cluster.local
        }
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
